### ISSUE TITLE
Button Update 

### ISSUE THREAD

**Issue by melmdesign** [sumup/circuit-ui#103]
## Buttons Update 

Related to 👉 #23 

- Added icon buttons
- Added grey button (Basic) spec

### Naming Convention for Button Styles
- Basic (Grey)
- Primary (Blue)
- Destructive (Red)
- Secondary (Outline)

### Basic Button Styling

/* BasicButton/Default: */

background: #GREY-100;
border: 1px solid #GREY-300;
box-shadow: inset 0 1px 0 1px rgba(255,255,255,0.06);
border-radius: 4px;

/* BasicButton/Hover: */

background: #GREY-300;
border: 1px solid #GREY-500;
box-shadow: inset 0 1px 0 1px rgba(255,255,255,0.06);
border-radius: 4px;

/* BasicButton/Active: */

background: #GREY-300;
border: 1px solid #GREY-500;
box-shadow: inset 0 2px 4px 0 #GREY-500;
border-radius: 4px;

/* BasicButton/Focus: */

background: #GREY-100;
border: 2px solid #GREY-300;

## Icon Button
Acts as element with standard button
24px Container with 16px Icon
Utilises same spacing as each button size
Icon should be easily fillable with colour if needed (Social Media icons etc.)

**Comment by melmdesign** [comment]
cc @felixjung

**Comment by connor-baer** [comment]
I'd like to suggest a slightly different naming scheme: 

    Primary (Blue)
    Secondary (Grey)
    Destructive (Red)

    Ghost (Outline)
    Flat (Text only)

Primary, secondary, destructive... modify the color.
Ghost and flat modify the shape.

**Comment by connor-baer** [comment]
Alright, just discussed this with @felixjung — for now, I'm just gonna implement the new basic (grey) variant.

We should discuss what other button styles we really need (e.g. there's no outline button yet). We don't want to end up with hundreds of button styles like now 😜
