### ISSUE TITLE
[Docs] Add a concrete example of an app using Circuit-ui

### ISSUE THREAD

**Issue by cristianoliveira** [sumup/circuit-ui#126]
I've received this feedback from a developer that tried to use the lib. He wanted to see a concrete usage of the circuit-ui. He mentioned that a "Todo list" is the most common sample app.
He mentioned that the storybook wasn't enough for him because there weren't examples of configuring (package and theme) there.

So I am opening this issue just to keep track of it and provide it in the future :)

It's kind of simple task so I'm gonna mark it as `good first issue` for who wants to contribute

**Comment by mlent** [comment]
@cristianoliveira @connor-baer Does this help now that we have:

https://github.com/sumup/create-sumup-next-app
https://github.com/sumup/create-sumup-react-app

? We could add links to both in the README.

**Comment by connor-baer** [comment]
@ugobriasco You were the one who initially gave this feedback, right? What do you think? 👆

**Comment by ugobriasco** [comment]
@connor-baer I'm going to give them a try and see if stepping in is smooth. Stay tuned

**Comment by mlent** [comment]
@ugobriasco Have a look here if you're still missing something, @felixjung is updating our CRA https://github.com/sumup/create-sumup-react-app/pull/1
