### ISSUE TITLE
[Toggle] not fully reponsive

### ISSUE THREAD

**Issue by ugobriasco** [sumup/circuit-ui#140]
The[ Toggle with explanation ](https://sumup.github.io/circuit-ui/?selectedKind=Toggle&selectedStory=Toggle%20with%20no%20bottom%20margin&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) has no fixed width relative to its label. This makes it shrinking whenever the label changes its text. Here an example:

![device-2018-04-17-110017](https://user-images.githubusercontent.com/9917415/38860158-d65cc2a4-422f-11e8-9ba7-3ce0cddca053.png)

The things are getting worse when the average amount of letters/word in the label is increasing (e.g. in German), like in this example (screen width 375px)

![screen shot 2018-04-17 at 14 03 08](https://user-images.githubusercontent.com/9917415/38868735-68b0ed02-4248-11e8-8b01-0ee7a46e2b9a.png)

In extreme cases this might cause relevant usability issues.

**Comment by connor-baer** [comment]
This looks more like a difference between the active/inactive states. Can you check if that's the case?

**Comment by ugobriasco** [comment]
@connor-baer the frame between active and inactive should not change. Further, the label is messing up the design using trouble-kind languages like German.

**Comment by connor-baer** [comment]
Of course it shouldn't change 🙃 Just wanted to get to the bottom of the issue. Looks like it's the label width after all.

**Comment by connor-baer** [comment]
Closed by #142.
