### ISSUE TITLE
[Card] additional margin right on mobile view

### ISSUE THREAD

**Issue by ugobriasco** [sumup/circuit-ui#141]
[Cards](https://sumup.github.io/circuit-ui/?selectedKind=Card&selectedStory=Card%20with%20shadows&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) have an extra margin right whenever the screen width is <430px (aka mobile view portrait).

![screen shot 2018-04-17 at 10 41 24](https://user-images.githubusercontent.com/9917415/38860712-20b4b0b8-4231-11e8-8018-05f97ba8241f.png)

this can generate some responsiveness headaches

**Comment by connor-baer** [comment]
@ugobriasco Do you know if this issue is still happening?

**Comment by ugobriasco** [comment]
It seems not, closing it.
