### ISSUE TITLE
Tag Visual Tweak: Remove grey stroke from selected state

### ISSUE THREAD

**Issue by melmdesign** [sumup/circuit-ui#156]
Related to: #65 

![image](https://user-images.githubusercontent.com/24547232/39690230-a7ee8786-51d9-11e8-9462-5d97ed21fe23.png)

Grey stroke around tag button should be removed ☝️

**Comment by davidbucka** [comment]
i think this can be closed: [commit](https://github.com/sumup/circuit-ui/commit/3baec642a75a833ce6d03427af656ec73df889ba)

**Comment by connor-baer** [comment]
You're right, thanks @davidbucka!
