### ISSUE TITLE
masked input erroring on init

### ISSUE THREAD

**Issue by nicholas-b-carter** [sumup/circuit-ui#174]
When rendering the maskedInput component, an error message is displayed ```e.map is not a function```, this can be seen/reproduced at 
https://sumup.github.io/circuit-ui/?selectedKind=MaskedInput&selectedStory=Default%20MaskedInput&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by felixjung** [comment]
Hi @nicholas-b-carter, Thanks for reporting the issue. We'll look into it. Personally, I've seen this issue happen a lot during development, whenever the `mask` prop is missing on the `MaskedInput` component. While this prop is not directly used by `MaskedInput`, it is being forwarded directly to the underlying `TextMaskInput` from `react-text-mask`. That's where the error happens.

In this particular case, I can see the story does not set the `mask` property. I'm relatively confident this is the cause of the error you're seeing. We'll make a change to the story to document the usage of this component better.
