### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by artsheeps** [sumup/circuit-ui#20]
![desktop hd copy 2](https://user-images.githubusercontent.com/7701850/35060497-ead52c88-fbbe-11e7-9f1f-48a42a2120f0.png)

Font-size / Line-height marked in each title. If we want to stick to the bit, byte... Naming I suggest to use the order from above. Like this, we can still add smaller and bigger ones. 

The font Used is Aktiv Grotesk (Regular/XBold) and can currently only be used on Adobe. They suggest the following implementations:

```html
<link rel="stylesheet" href="https://use.typekit.net/dxb5kvg.css">
```

```css
<style>
  @import url("https://use.typekit.net/dxb5kvg.css");
</style>
```

```javascript
<script>
  (function(d) {
    var config = {
      kitId: 'dxb5kvg',
      scriptTimeout: 3000,
      async: true
    },
    h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
  })(document);
</script>
```

More infos here: https://helpx.adobe.com/typekit/using/embed-codes.html

**Comment by artsheeps** [comment]
FYI The ones marked with the blue bar are the main Styles for the Dashboard

**Comment by felixjung** [comment]
How are we supposed to name the variables here? We store font sizes and line heights differently. At which size should line heights start? Kilo? Currently it looks like this:

```javascript
export const fontSize = {
  kilo: '17px',
  mega: '29px',
  giga: '22px',
  tera: '24px',
  peta: '28px',
  exa: '36px',
  zetta: '42px'
};

export const lineHeight = {
  kilo: '24px',
  mega: '32px',
  giga: '44px',
  tera: '48px'
};
```

**Comment by felixjung** [comment]
What should we call the different font weights in the theme. Keep with the type face's definitions or use something like `light`, `regular`, `bold`?

**Comment by felixjung** [comment]
I'm also wondering how this is affected by different screen sizes. Does a mega body turn into a kilo body on mobile? Or do each of these have different font sizes and line heights at different breakpoints? 😕

**Comment by felixjung** [comment]
I guess this would be easier to handle with `rem`s. 😁

**Comment by artsheeps** [comment]
I would use regular and bold as these are also inline with the definition from the font itself. So far we only use the two mentioned above.

Regarding the different screen sizes its probably easier/safer to define different sizes within the original mega, without changing the variables.

**Comment by felixjung** [comment]
This is done for now. Let's open a new issue once we get to responsiveness.
