### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by artsheeps** [sumup/circuit-ui#21]
![artboard](https://user-images.githubusercontent.com/7701850/35061469-a0789c3a-fbc1-11e7-99a7-a5e4e47a7714.png)

We're using a 4px baseline grind. Therefore all spacings (except the smallest one - bit) should be divisible by 8px.

![artboard copy](https://user-images.githubusercontent.com/7701850/35061620-154f30fa-fbc2-11e7-8664-7f7ad2c7af66.png)

For bigger spacings we added a 'double-spacing'
These are not supposed to be used for any interface and are only designed for the big paddings that we need on the marketing website - not sure if it's worth it implementing all of them, but to me just having the regular ones x2 seems easy, even if we will have some duplicates.

**Comment by felixjung** [comment]
So, I've added these spacing to the theme. We'll implement the 2x variants via a prop on the components that need it (i.e., `doubleSpacing`). In a project that uses these components and always need double-spacing (i.e., marketing site), you can easily create an always 2x variant in emotion:

```javascript
import withProps from 'recompose/withProps';
import { omit } from 'lodash/fp';
import UiSection from 'circuit-ui/section';

const Section = withProps({ doubleSpacing: true })(uiSection);
Section.propTypes = omit(['doubleSpacing'])(UiSection.propTypes)
export default Section;
```

**Comment by melmdesign** [comment]
![single spacing](https://user-images.githubusercontent.com/24547232/35225808-92d6e49e-ff89-11e7-92d8-f428f495f7ac.png)
![double spacing](https://user-images.githubusercontent.com/24547232/35225810-94d0834a-ff89-11e7-9a5d-46d8d4509af1.png)

Updated to include 12/24px spacings
