### ISSUE TITLE
Text-spacing combinations

### ISSUE THREAD

**Issue by artsheeps** [sumup/circuit-ui#22]
![artboard 2](https://user-images.githubusercontent.com/7701850/35061819-a21b3970-fbc2-11e7-9521-3d0b0d33ae8b.png)

**Comment by felixjung** [comment]
Once we have the regular typography components we can make variants with spacing like so:

```javascript
import UiSection from 'circuit-ui/section'
import styled from 'react-emotion'

const bottomMargin = size => ({ theme }) => css`
  margin-bottom: ${theme.spacing[size]};
`

export default const Section = styled(UiSection)(
  bottomMargin('giga')
);
```

**Comment by artsheeps** [comment]
![typography](https://user-images.githubusercontent.com/7701850/35720456-17f00022-07ee-11e8-801e-25b6d8b02bec.png)
