### ISSUE TITLE
 "Copy link" button on the referrals section does not copy to the clipboard on iOS

### ISSUE THREAD

**Issue by joaovtg** [sumup/circuit-ui#223]
When using a **iOS** device with either Safari or Chrome the `Copy Link` only selects the text for the user to then click again to effectively copy (also zooming the screen). 

The expected behaviour should be to copy the link directly to the device's clipboard, which is already happening on Android devices.

Here's a [video](https://drive.google.com/file/d/1-IC8Jjp5ZTbYdZ2Y3g_g3CA86rdP012d/view?usp=sharing) of what happens.

**Comment by mlent** [comment]
Hey @joaovtg - I think you want to open a ticket for this in JIRA in the Referral's squad jira board. The copy link button isn't part of circuit UI but just part of that screen.

cc @herberthenrique

**Comment by joaovtg** [comment]
Thanks, Monica! @herberthenrique is already on it ;)
