### ISSUE TITLE
Button flat and flat primary variations - active and focus state design

### ISSUE THREAD

**Issue by GuyLivni** [sumup/circuit-ui#234]
Flat button has some design issues that we should review.
* **In Flat** state when active it gets p900 color, which one should it really get? 
![1 flat active state](https://user-images.githubusercontent.com/6113581/42702069-a5c46894-86c8-11e8-8757-d8738c536632.gif)

* **In Flat** state when focused it gets dark border, should it be there?
![2 border flat color](https://user-images.githubusercontent.com/6113581/42702067-a59375cc-86c8-11e8-88d3-5bafded27eca.png)

* **In primary and flat** state it has no border, but on hover it adds border that shifts the layout should it be there? if it does maybe the flat + primary button variation should start with:
```
    border-color: transparent;
    border-width: 1px;
```
![3 primary flat state](https://user-images.githubusercontent.com/6113581/42702068-a5acc694-86c8-11e8-9e32-d8ef555964b2.gif)

**Comment by mlent** [comment]
@GuyLivni The way we could do this is using the box shadow to create a "fake" inner border, instead of the transparent border which will visually change the dimensions of the button.

For sure there are examples of this in the repo. Check out the Card, I'm pretty sure it's covered there.

**Comment by GuyLivni** [comment]
@mlent I am not sure what is the intended design, currently hover state is just not covered when it is primary + flat button variation, the border it gets on hover is cascaded from primary variation. Is there supposed to be a border on hover if there is no border on default state for flat+primary?

**Comment by connor-baer** [comment]
Fixed by #281.
