### ISSUE TITLE
Form Fields

### ISSUE THREAD

**Issue by majahoughton** [sumup/circuit-ui#26]
![image](https://user-images.githubusercontent.com/31246945/35227461-7752ce90-ff8e-11e7-9811-5cd27b69d666.png)

**Comment by majahoughton** [comment]
/* Label: */
Body Large Giga - **bold**

```css
## Default
background: #FFFFFF;
border: 1px solid #D8DDE1;
box-shadow: inset 0 0 0 1px rgba(102,113,123,0.25), inset 0 1px 2px 0 rgba(102,113,123,0.21);
border-radius: 4px;
/* Text: */
Body Large Mega
color: #9DA7B1;

## Active/Focused
border: 1px solid #3388FF;
box-shadow: inset 0 0 0 1px rgba(102,113,123,0.25), inset 0 1px 2px 0 rgba(102,113,123,0.21);
/* Text: */
Body Large Mega  

## Error
background: #FFE6E1;
border: 1px solid #FF7559;
/* Text: */
Body Large Mega 

## Optional
background: #FAFBFC;
border: 1px dashed #D8DDE1;
/* Text: */
Body Large Mega
color: #9DA7B1;

## Disabled
opacity: 0.5;
background: #FAFBFC;
border: 1px solid #D8DDE1;
/* Text: */
Body Large Mega
color: #D8DDE1;

## With-Icon
border: 1px solid #D8DDE1;
box-shadow: inset 0 0 0 1px rgba(102,113,123,0.25), inset 0 1px 2px 0 rgba(102,113,123,0.21);
**Icon style not defined**
/* Text: */
Body Large Mega

## Prefix
/* Prefix Text: */
Body Large Mega
color: #D8DDE1;

/* Text: */
Body Large Mega

## Suffix
/* Text: */
Body Large Mega

/* Suffix Text: */
Body Large Mega
color: #2A7AE6;

```

**Comment by felixjung** [comment]
This isn't really clear to me.

- Which `font-size`/`line-height` combos are these, really?
- Are these inset box-shadows correct? When rendered, they look very different from the mockup above.

I guess I'll have some more tomorrow. Nighty night 🌙 ⭐️ 🌃

**Comment by majahoughton** [comment]
font-size - 15px
line-height - 24px

I checked the values of the inset shadow, they are the correct ones from the mockup.
box-shadow: inset 0 0 0 1px rgba(102,113,123,0.25), inset 0 1px 2px 0 rgba(102,113,123,0.21);

**Comment by felixjung** [comment]
@majahoughton in the password input example with show/hide. What is the desired behavior for the text button? What are the various button states? Are there any?

**Comment by mlent** [comment]
@majahoughton @artsheeps Where are the less aggressive inputs? @felixjung Did you already update them?

**Comment by felixjung** [comment]
These elements are all kind of done. But I see a lot of open points that we need to revisit:
- The border/inner shadow doesn't look like in the design. Despite identical box-shadow css.
- I need a new and properly sized down arrow icon.

@majahoughton, let's sit down and look and play with it a bit.

**Comment by artsheeps** [comment]
![artboard](https://user-images.githubusercontent.com/7701850/35859267-b49f0f2c-0b3f-11e8-92a1-11f41f413a45.png)

☝🏻updated error message
