### ISSUE TITLE
[feature] Add color palette on Storybook

### ISSUE THREAD

**Issue by cristianoliveira** [sumup/circuit-ui#260]
When dealing with colors is hard to guess the colors we have available just by looking at the theme object.

Would be nice to have it listed on Storybook.

**Comment by connor-baer** [comment]
I believe this will be a part of the documentation.

cc @ilyanoskov

**Comment by ilyanoskov** [comment]
@cristianoliveira yes, we have it in circuit-docs! coming very soon, in 1-2 days

**Comment by ilyanoskov** [comment]
@cristianoliveira https://sumup.github.io/circuit-ui

**Comment by cristianoliveira** [comment]
👍
