### ISSUE TITLE
Drop down menu with phone number's country code and country flag

### ISSUE THREAD

**Issue by vpenkoff** [sumup/circuit-ui#289]
Hello!!!

Is it possible to have a component, which contains a list of phone number's country code and a flag, similar to [this](https://intl-tel-input.com/) one?

**Comment by connor-baer** [comment]
Hi Viktor, this is absolutely possible, however, we'd need more specific specs and a design before we can implement it. Ideally, this would be handled by a specific squad (conversion maybe?). That's why Jira is a better place to request new components.
