### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by artsheeps** [sumup/circuit-ui#31]
The basic card component needs to combine shadows, background and spacings.

**Comment by melmdesign** [comment]
![example spacing](https://user-images.githubusercontent.com/24547232/35438425-c6e3fe4c-0296-11e8-976e-a97c24722aad.png)

- Cards utilise spacing sizes ranging from Kilo to Giga. 
- Spacings are in an overlay on Sketch — you can turn off visibility for this in the layers panel. 
- The card background uses #FFFFFF and #FAFBFC is used in the centre of mockups to signify a different area — the "Content Area" — but in actual implementation will maintain the same #FFFFFF background colour as the entire card container. 

Added card specs to Abstract, can be found [here](https://share.goabstract.com/ab8f0e61-b5b9-4c52-8e52-eecaa3aa0a97)
