### ISSUE TITLE
Checkbox and Radio

### ISSUE THREAD

**Issue by artsheeps** [sumup/circuit-ui#32]

**Comment by majahoughton** [comment]
![image](https://user-images.githubusercontent.com/31246945/35341707-99806452-0126-11e8-9d08-7f30412d1444.png)

**Comment by majahoughton** [comment]
The checkboxes & radio buttons share the same CSS as their corresponding form field.

## Focus
```
background: #FFFFFF;
border: 2px solid #3388FF;
box-shadow: inset 0 0 0 1px rgba(102,113,123,0.25), inset 0 1px 2px 0 rgba(102,113,123,0.21);
border-radius: 3px;
```

**Comment by mlent** [comment]
@majahoughton @artsheeps Should these be updated now that you guys updated the error inputs to look less aggressive?

**Comment by artsheeps** [comment]
yes, going to update them as well.

**Comment by connor-baer** [comment]
@melmdesign @majahoughton @artsheeps  In the unselected, unfocused state, the input borders have a contrast ratio of 1.37. That's waaaaay too low to be accessible. I suggest to change the border-color to `#9DA7B1` (2.44 contrast) or even `#5C656F` (5.92 contrast ratio). WDYT?
