### ISSUE TITLE
Messages/Alerts

### ISSUE THREAD

**Issue by artsheeps** [sumup/circuit-ui#34]
- [ ] Flash Alert
- [ ] Persistent alert

### Can contain:
Heading
Related message colour
Icon
Link for action (Close)
Inline Messages

**Comment by melmdesign** [comment]
![slice 6](https://user-images.githubusercontent.com/24547232/35969590-a748958a-0cc7-11e8-940f-178ef99a59c5.png)
![slice 6](https://user-images.githubusercontent.com/24547232/35969850-81b5e088-0cc8-11e8-8c7a-471d2b3d516c.png)


![slice 5](https://user-images.githubusercontent.com/24547232/35969440-178c3a96-0cc7-11e8-93b8-d6bc597c49a0.png)


### Persistent Alerts 

- Non-dismissable
- Can be globally persistent (in which case they are in banner form drawn over the UI)
- Can also be persistent for only a specific page (taking the form of a card at the top of related screen)
- Only dismissable by carrying out a specific action (e.g. Documents have been uploaded)
- Action area should link to the location required to perform said action
- Copy should highlight and reflect the importance of the issue
- The nature of alerts should be obvious and consistently apparent 
- Call to action label should be positive as a way to solve an issue and should NOT use alert colours related to the alert state


### Message Alerts

- Message alerts are to be used to inform merchants of new features, updates
- Could also be used as an area for new feature announcements

### Flash Alerts

- Non-dismissable but auto-hiding by nature
- Flash alerts are responses to actions undertaken (e.g. Document uploaded, settings saved, refund success etc.)
