### ISSUE TITLE
Upgrade Emotion

### ISSUE THREAD

**Issue by felixjung** [sumup/circuit-ui#340]
Emotion has just been updated to version 10. It comes with some niceties and a cleaner API. Most of the upgrade can be done with a codemod through ESLint, so it should be fine.

Problem of course is, that all our apps will also have to update at some point. But that's how the world works. 😁

**Comment by fernandofleury** [comment]
No

**Comment by connor-baer** [comment]
Care to elaborate @fernandofleury?

**Comment by fernandofleury** [comment]
it requires us to add a pragma comment on every file: https://github.com/emotion-js/emotion/blob/master/docs/migrating-to-emotion-10.md#thinking

**Comment by connor-baer** [comment]
Are you concerned about the work, do you not like the concept or is it something else?

**Comment by felixjung** [comment]
He's just trolling me. Although, he also doesn't like changing "standard" React usage. I'm like ¯\_(ツ)_/¯ .
