### ISSUE TITLE
Drop target container

### ISSUE THREAD

**Issue by artsheeps** [sumup/circuit-ui#36]
Can contain:
- [ ]   Text
- [ ]   Icon
- [ ]   Image/illustration
- [ ]   Secondary information layer (Tooltip)

**Comment by melmdesign** [comment]
The Drop Target Container should maintain at least similar styling to input fields as it is a method of input (file upload)

### States
- [ ] Default
- [ ] Hover with Document
- [ ] Failed Upload / Incorrect File Type
- [ ] Upload in Progress 

### Information to display

- [ ] Heading
- [ ] Compatible file types
- [ ] Drop target area
- [ ] Button for manual file selection
- [ ] Icon?
- [ ] Loading Indicator (Perpetual vs. “Real” )
- [ ] Multiple documents 
  - [ ] Status 
  - [ ] Name 
  - [ ] Filetype
