### ISSUE TITLE
list elements

### ISSUE THREAD

**Issue by artsheeps** [sumup/circuit-ui#37]
Ordered and unordered list

**Comment by melmdesign** [comment]
![image](https://user-images.githubusercontent.com/24547232/35514874-e6a65aae-0507-11e8-88fd-0b8ca9236f24.png)


**Added Ordered / Unordered List Variations** 
Can be found on Abstract [here](https://share.goabstract.com/61a17593-e843-4b85-bab3-23a68646f4c2)

**Spec**
- Uses kilo spacing for ordered and unordered list
- Bottom margin between line also uses kilo spacing
- Ordered list numbers uses Subheading/Large/Kilo text
- Both lists us Body/Large/Mega for text

**Comment by felixjung** [comment]
What are these supposed to look like in terms of indentation? Are they indented from the surrounding main text? What should they look like when an item has multiple lines?

**Comment by artsheeps** [comment]
@melmdesign can you upload the full design that answers Felix questions?

**Comment by felixjung** [comment]
Yet one more question so @mlent will have the perfect list design this afternoon: have you thought about indentation for nested lists? I think at least 2 levels deep needs to be considered.

**Comment by melmdesign** [comment]
Assume the same indentation as previous level in this case. 

Each level of indentation should behave the same way as previous level. i.e. If 1st level indents 16px, second level should indent 32px (2x) and 3rd level should indent 48px (3x)

cc @mlent @felixjung

**Comment by melmdesign** [comment]
![slice 2](https://user-images.githubusercontent.com/24547232/35669570-cb2b3d64-0735-11e8-9ecf-b380ba94e95a.png)
