### ISSUE TITLE
Enable custom styles in Sidebar

### ISSUE THREAD

**Issue by robinmetral** [sumup/circuit-ui#461]
## Component to amend

`Sidebar`

## Context

The new `Sidebar` component has `position: relative`:
https://github.com/sumup/circuit-ui/blob/03b336f7eda059e2e322bda0db323fa92991e604/src/components/Sidebar/Sidebar.js#L44

...but the Dashboard needs it to be `fixed` in order to migrate from the legacy `SideNav` component.

Allowing custom CSS in this component would prevent it from overriding our custom styles.

**Comment by connor-baer** [comment]
Resolved in https://github.com/sumup/circuit-ui/pull/462.
