### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by artsheeps** [sumup/circuit-ui#53]
- Badges are used to inform merchants of the status of a piece of information. For example, within the order history, a badge would show “Payment Pending” if money is waiting to be sent. 
- Available in the apparent alert colour

_https://semantic-ui.com/elements/label.html_

**Comment by cristianoliveira** [comment]
This one looks a good one to start helping. :)
Could I get this one?

**Comment by connor-baer** [comment]
@cristianoliveira 😉

**Comment by melmdesign** [comment]
Duplicate of Atom instance
