### ISSUE TITLE
Selectors

### ISSUE THREAD

**Issue by artsheeps** [sumup/circuit-ui#55]
- Selectors act as buttons that have multiple options ( more than 2 )
- Sectors can be enabled but only one can be enabled at one time
- If a selector does not require a heading, icons & imagery then we recommend a CHECKBOX & RADIO BUTTON
- It must be easy to know which item is selected. Selected states must be clear

- [x] Shape
  - [x] Active
  - [x] Default
  - [ ] Hover
- [x] Colour
- [x] Text
- [x] Icon
- [x] Imagery

**Comment by majahoughton** [comment]
![image](https://user-images.githubusercontent.com/31246945/35978916-320dec96-0ce7-11e8-9daa-f2500db1271c.png)
![image](https://user-images.githubusercontent.com/31246945/35978926-374f925e-0ce7-11e8-8242-cd72dc83cb87.png)

**Comment by majahoughton** [comment]
![image](https://user-images.githubusercontent.com/31246945/36018707-0bbe5238-0d7d-11e8-96c7-7af7e692107e.png) ![image](https://user-images.githubusercontent.com/31246945/36018712-11348eda-0d7d-11e8-8681-b30e321294e1.png)
