### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by melmdesign** [sumup/circuit-ui#64]
Icons for general usage. Various sizes will be necessary.

For use in various locations in apps/sites

**Comment by artsheeps** [comment]
Currently we defined the following Icon sizes:

- 16x16px - kilo
- 24x24px - mega
- 32x32px - giga
- 48x48px - tera

So far we're only using the 16 and 24 px one. Let's only implement those for now and see if we even need the bigger ones. Attached one sample svg icon.

![artboard 2](https://user-images.githubusercontent.com/7701850/35801361-5e7d20c6-0a6c-11e8-85d6-2f67d4d4e0d6.png)

[Calendar.svg.zip](https://github.com/sumup/circuit-ui/files/1698959/Calendar.svg.zip)

**Comment by connor-baer** [comment]
We do not need a special `<Icon>` component since we import SVG as React components directly. We could add the sizes as constants somewhere, so keep them consistent and easy to update.
