### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by melmdesign** [sumup/circuit-ui#65]
- Tags can be clickable & link to something
- They can be used everywhere
- When applied to search and filter, they can be dismissible
- Tags in the search can be predefined and selectable. Results in filtering with predefined tags

- [x] Icon
- [x] Text
- [x] Dismiss action

**Comment by melmdesign** [comment]
![tags](https://user-images.githubusercontent.com/24547232/35650274-cbc367ce-06db-11e8-8cac-acc1f4ac643e.png)

### Abstract page for tags [here](https://share.goabstract.com/2e0b7414-77d7-4cc8-90ee-08c5ffd9f85b)

Will add complete spec ASAP

**Comment by melmdesign** [comment]
## Tags

### Icon Tag
![slice 4](https://user-images.githubusercontent.com/24547232/35670540-277ef58a-0739-11e8-80e4-c3883e891bc4.png)

### Dismissable Tag
![slice 4](https://user-images.githubusercontent.com/24547232/35670582-3bce0896-0739-11e8-87a1-86f8b5807bc1.png)

## Tag Styling Spec
### Default State
```
/* BG: */
background: #GREY-100;
border: 1px solid #GREY-300;
box-shadow: inset 0 2px 0 0 #FFFFFF;
border-radius: 4px;
```

### Hover State
```
/* BG: */
background: #GREY-300;
border: 1px solid #GREY-500;
box-shadow: inset 0 2px 0 0 #GREY-100;
border-radius: 4px;
```

### Selected State
```
/* BG: */
background: #BLUE-500;
border: 1px solid #BLUE-700;
box-shadow: inset 0 2px 0 0 #BLUE-300;
border-radius: 4px;
```

## Details
### Icon Area
16px Square Container for Icon
Icon Fill: 
- Black — Default / Hover State
- White — Selected State

### Dismiss Button
Simple 8px * 8px "Close Button"
Default state fill: Grey—500 
Hover state fill: Grey—700

### Typography
- Mega Body Regular / Default Black

**Comment by artsheeps** [comment]
FYI 
Slightly updated the style above ☝🏻
