### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by melmdesign** [sumup/circuit-ui#66]
- Badges are used to inform merchants of the status of a piece of information. For example, within the order history, a badge would show “Payment Pending” if money is waiting to be sent. 
- Should be available in the apparent alert colours (Red 500, Green 500, Yellow 500, Blue 500)

**Comment by cristianoliveira** [comment]
It's probably the same as #53

**Comment by melmdesign** [comment]
@cristianoliveira deleted duplicate in molecules project — you can follow this instead

**Comment by melmdesign** [comment]
![slice 2](https://user-images.githubusercontent.com/24547232/35650901-053fff6a-06de-11e8-9d47-5846dcb686a2.png)

### Abstract Page [Here](https://share.goabstract.com/2e0b7414-77d7-4cc8-90ee-08c5ffd9f85b)

Will update with full spec ASAP

**Comment by melmdesign** [comment]
## Badge Spec

![slice](https://user-images.githubusercontent.com/24547232/35669209-9ded1170-0734-11e8-9fb5-b4187a244c20.png)


Badges will not always be interactable but let's bake in the ability for them to act as a button now and worry about where/when we might use that at a later point.

### Default Badge State
height: 20px;
padding: 0px 4px 0px 4px (Byte Padding Size Left/Right);
background-color: ALERT-500 (Red, Green, Yellow, Blue)

### Hover Badge State
background-color: ALERT-700 (Red, Green, Yellow, Blue)

### Active Badge State
background-color: ALERT-900 (Red, Green, Yellow, Blue)



### Typography
Centred White Subheading — Kilo sizing

**Comment by artsheeps** [comment]
![slice](https://user-images.githubusercontent.com/7701850/35719730-0fee7cf8-07eb-11e8-8db3-28c2a5001cae.png)
Update:
We would like to have an additional Variant that is circular and can contain up to 2 digits.
Stile stays the same as above
